echo ""
echo -e "\e[1;36m"
echo -e "\e[1;36mDigite a Host para gerar payloads!"
echo ""
echo -ne "\e[1;33mHOST: \e[1;36m";
read host
echo ""
echo -e "\e[1;32m"
echo "CONNECT [host_port][split][crlf]HTTP/1.0 [crlf]Host: $host[crlf][crlf]"
echo ""
echo "CONNECT / HTTP/1.1[crlf]Host: [rotate=$host;$host][crlf]Connection: Keep-Alive[crlf][crlf]"
echo ""
echo "CONNECT [host_port][split][lf]OPTIONS  HTTP/1.1[crlf]Host: [rotate=$host[crlf]"
echo ""
echo "CONNECT [host_port] [protocol][crlf][delay_split]GET $host HTTP/1.1[crlf]Host: $host [crlf][crlf]"
echo ""
echo "CONNECT / HTTP/1.1[crlf]Host: $host[crlf]Connection: Keep-Alive[crlf][crlf]"
echo ""
echo "[split][crlf]CONNECT [host_port][delay_split][crlf]PUT /? HTTP/1.0[crlf]Host: $host[crlf]"
echo ""
echo "CONNECT [split][lf] HTTP/1.0 [lf]Host: $host[lf]X-Online-Host: $host[lf]"
echo ""
echo "CONNECT [host_port][netData][split][lf]ACL /? HTTP/1.1[crlf]Host: $host[crlf]X-Forwarded-For: $host[crlf]Connection: Keep-Alive[crlf]"
echo ""
echo "MKCOL /? HTTP/CONNECT/Host: $host"
echo ""
echo "HEAD $host HTTP/1.1 Proxy-Connection: [host_port]Connection: Keep-Alive Host: $host"
echo ""
echo "PROPFIND $host HTTP/2[crlf]Host: $host[crlf]"
echo ""
echo "CONNECT [host_port][crlf]PROPPATCH $host HTTP/[host_port][crlf]Host: $host[crlf]"
echo ""
echo "ACL HTTP/2 Host: $host[protocol][lf]TCP\n \n"
echo ""
echo "CONNECT [host_port][split][crlf] HTTP/2 [crlf]Host: $host[crlf]"
echo ""
echo "CONNECT [host_port][split][lf] HTTP/2 [lf]Host: $host Proxy-Connection: close Connection-Keep-true Control-Cache: no-cache User-Agent: Yes [crlf]"
echo ""
echo ""
echo ""
echo -e "\e[1;31mClique em ENTER para voltar ao menu inicial..."
read foo
